import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import LoadingScreen from '@/components/LoadingScreens/LoadingScreen';
import { useEffect } from 'react';

export default function Home() {
  // useEffect(() => {
  //   const onPageLoad = () => {
  //     const worker = new Worker(
  //       //new URL('../wait5s.worker.js', import.meta.url)
  //       new URL('@/workers/wait5s.js', import.meta.url)
  //     );

  //     // Escucha el mensaje enviado por el Web Worker
  //     worker.onmessage = function (event) {
  //       console.log('Mensaje recibido:', event.data);
  //     };
  //     worker.postMessage('¡Hola Web Worker!');
  //   };
  //   if (document.readyState === 'complete') {
  //     onPageLoad();
  //   } else {
  //     window.addEventListener('load', onPageLoad);
  //     return () => {
  //       window.removeEventListener('load', onPageLoad);
  //       worker.terminate();
  //     };
  //   }
  // }, []);

  return (
    <>
      <LoadingScreen type="gradient-waves">
        <Image
          src="/assets/images/logo.png"
          alt="LOGO"
          width={184}
          height={198}
        />
      </LoadingScreen>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}
